# <u>**Part 5**



In [10]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

## **Exercise 41**

The following dataframe is given

* `np.random.seed(42)`
* `df = pd.DataFrame(data=np.random.randn(10), columns=['var1'])`

Implement the `sigmoid()` function using the numpy package

In [ ]:
np.random.seed(42)
df = pd.DataFrame(data=np.random.randn(10), columns=['var1'])

In [ ]:
df

var1
0  0.496714
1 -0.138264
2  0.647689
3  1.523030
4 -0.234153
5 -0.234137
6  1.579213
7  0.767435
8 -0.469474
9  0.542560

In [ ]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [ ]:
df['var1_sigmoid'] = df['var1'].apply(sigmoid)
df

var1  var1_sigmoid
0  0.496714      0.621687
1 -0.138264      0.465489
2  0.647689      0.656489
3  1.523030      0.820984
4 -0.234153      0.441728
5 -0.234137      0.441732
6  1.579213      0.829093
7  0.767435      0.682966
8 -0.469474      0.384741
9  0.542560      0.632408

## **Exercise 42**



Load the 42.csv file into the DataFrame.

Then, using the StandardScaler class from the scikit-learn package, standardize all the variables.

In [ ]:
df = pd.read_csv('42.csv')
df.head()

var1   var2    var3    var4     var5
0  12.47  18.60   81.09   481.9  0.09965
1  18.94  21.31  123.60  1130.0  0.09009
2  15.46  19.48  101.70   748.9  0.10920
3  12.40  17.68   81.47   467.8  0.10540
4  11.54  14.44   74.65   402.9  0.09984

In [ ]:
scaler = StandardScaler()
scaler.fit(df)

StandardScaler()

In [ ]:
df_scaled = scaler.transform(df)
df_scaled

array([[-4.78538093e-01, -2.13716784e-01, -4.58680543e-01,
        -5.11379891e-01,  6.83084080e-02],
       [ 1.37424404e+00,  3.89500006e-01,  1.29254696e+00,
         1.40549685e+00, -6.12226925e-01],
       [ 3.77693525e-01, -1.78382691e-02,  3.90362007e-01,
         2.78322453e-01,  7.48131884e-01],
       [-4.98583649e-01, -4.18498868e-01, -4.43026193e-01,
        -5.53083273e-01,  4.77626208e-01],
       [-7.44857626e-01, -1.13968795e+00, -7.23980593e-01,
        -7.45037138e-01,  8.18336918e-02],
       [ 1.84961008e+00,  2.17466556e+00,  1.97227535e+00,
         1.80478455e+00,  1.36032894e+00],
       [ 2.25338486e+00,  5.20827647e-01,  2.26476453e+00,
         2.44660256e+00,  5.41693341e-01],
       [ 9.81923864e-01, -1.00390852e+00,  9.38264283e-01,
         8.88197447e-01, -1.56907231e-02],
       [-2.29400465e-01, -8.23611251e-01, -2.36223980e-01,
        -3.98692028e-01, -1.56907231e-02],
       [-6.90360146e-02, -6.54443443e-01, -1.34058744e-01,
        -1.63851706e-01

In [ ]:
type(df_scaled)

numpy.ndarray

In [ ]:
df = pd.DataFrame(df_scaled, columns=['var1', 'var2', 'var3', 'var4', 'var5'])
df

var1      var2      var3      var4      var5
0   -0.478538 -0.213717 -0.458681 -0.511380  0.068308
1    1.374244  0.389500  1.292547  1.405497 -0.612227
2    0.377694 -0.017838  0.390362  0.278322  0.748132
3   -0.498584 -0.418499 -0.443026 -0.553083  0.477626
4   -0.744858 -1.139688 -0.723981 -0.745037  0.081834
..        ...       ...       ...       ...       ...
138  0.142874 -0.961617  0.146072 -0.008573  1.032875
139  0.088465  0.146878  0.093341 -0.035784  0.002106
140 -0.888040 -0.607700 -0.877640 -0.832880  0.641353
141  1.623382  0.576475  1.556199  1.789996 -0.027080
142 -1.111405 -1.633836 -1.090622 -0.985497  0.090376

[143 rows x 5 columns]

### **Exercise 44**

Implement the entropy() function using the numpy package. Round the result to four decimal places.

$Entropy = \sum_{k=1}^{n}{p_i*log_2(p_i)}$

Then the following df DataFrame is given

<pre>
    val_1   val_2
0   0.01    0.99
1   0.11    0.89
2   0.21    0.79
3   0.31    0.69
4   0.41    0.59
5   0.51    0.49
6   0.61    0.39
7   0.71    0.29
8   0.81    0.19
9   0.09    0.09
</pre>

Using the implemented function, calculate the entropy for each pair in this DataFrame and assign to the 'entropy' column.


In [ ]:
def entropy(x):
    return np.round(-np.sum(x * np.log2(x)), 4)

In [ ]:
data_dict = {
    'val_1': np.arange(0.01, 1.0, 0.1),
    'val_2': 1- np.arange(0.01, 1.0, 0.1)
}

In [ ]:
df = pd.DataFrame(data_dict)
df

val_1  val_2
0   0.01   0.99
1   0.11   0.89
2   0.21   0.79
3   0.31   0.69
4   0.41   0.59
5   0.51   0.49
6   0.61   0.39
7   0.71   0.29
8   0.81   0.19
9   0.91   0.09

In [ ]:
df['entropy'] = [
    entropy([row[1][0], row[1][1]]) 
    for row in df.iterrows()
]

In [ ]:
df

val_1  val_2  entropy
0   0.01   0.99   0.0808
1   0.11   0.89   0.4999
2   0.21   0.79   0.7415
3   0.31   0.69   0.8932
4   0.41   0.59   0.9765
5   0.51   0.49   0.9997
6   0.61   0.39   0.9648
7   0.71   0.29   0.8687
8   0.81   0.19   0.7015
9   0.91   0.09   0.4365

### **Exercise 45**

The 45.csv file contains the predictions based on the certain multi-class classification model (3 classes). The y_true column describes the actual values, and the y_pred column describes the values predicted by the model.

Using the accuracy_score( ) function from the scikit-learn package, calculate the accuracy of this model.

In [ ]:
predictions = pd.read_csv('45.csv')
acc = accuracy_score(predictions['y_true'], predictions['y_pred'])
print(f'Accuracy: {acc:.4f}')

Accuracy: 0.7241


### **Exercise 46**

The 45.csv file contains predictions based on the certain multi-class classification model (3 classes). The y_true column describes the actual values, and the y_pred column describes the values predicted by the model.

Use the confusion_matrix( ) function from the scikit-learn package to calculate the confusion matrix and print it to the console.

In [3]:
predictions = pd.read_csv('45.csv')
cm = confusion_matrix(predictions['y_true'], predictions['y_pred'])
print(cm)

[[ 6  1  0]
 [ 3 10  2]
 [ 0  2  5]]


### **Exercise 47**

The following arrays are given:

 * ```X_train, y_train```
 * ```X_test, y_test```

 generated with the following code

```np.random.seed(42)```<br>
```raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)``` <br>
```data = raw_data[0]```<br>
```target = raw_data[1]```<br>
```X_train, X_test, y_train, y_test = train_test_split(data, target)```

Using the DecisionTreeClassifier class from the scikit-learn package, create classification model (leave the default arguments). Train the model on the train set and evaluate on the test set.

In [6]:
np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]
 
X_train, X_test, y_train, y_test = train_test_split(data, target)

In [7]:
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)
acc = classifier.score(X_test, y_test)
print(f'Accuracy: {acc:.4f}')

Accuracy: 0.9020


### **Exercise 48**

Using the DecisionTreeClassifier class from the scikit-learn package, create classification model (set max_depth=6). Train the model on the train set and evaluate on the test set.

In [8]:
classifier = DecisionTreeClassifier(max_depth=6)
classifier.fit(X_train, y_train)
acc = classifier.score(X_test, y_test)
print(f'Accuracy: {acc:.4f}')

Accuracy: 0.9280


### **Exercise 49**

Using the DecisionTreeClassifier class from the scikit-learn package, create a classification model (set max_depth=6 and min_samples_leaf=6). Train the model on the train set and evaluate on the test set.

In [9]:
classifier = DecisionTreeClassifier(max_depth=6, min_samples_leaf=6)
classifier.fit(X_train, y_train)
acc = classifier.score(X_test, y_test)
print(f'Accuracy: {acc:.4f}')

Accuracy: 0.9300


### **Exercise 50**

Using the DecisionTreeClassifier class and grid search method (GridSearchCV class - set scoring='accuracy', cv=5) find the optimal values of the max_depth and min_samples_leaf arguments. Search for parameter values from the following:

* for max_depth -> np.arange(1, 10)
* for min_samples_leaf -> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20]

Train the model on the train set and evaluate on the test set. In response, print founded optimal values of max_depth and min_samples_leaf to the console.



In [11]:
classifier = DecisionTreeClassifier()
 
params = {'max_depth': np.arange(1, 10),
         'min_samples_leaf': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20]}
 
grid_search = GridSearchCV(
    classifier, 
    param_grid=params, 
    scoring='accuracy', 
    cv=5
)
grid_search.fit(X_train, y_train)
print(grid_search.best_params_)

{'max_depth': 6, 'min_samples_leaf': 6}
