# <u>**Part 4**



In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import datasets
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import PolynomialFeatures

### **Exercise 31**

Load the breast cancer data into the data and target variables.

Using the *train_test_split()* function from the *scikit-learn* package, split the data (data and target) into train and test set. Set the *random_state=40* and the test size to 25%. Show the shapes of the arrays.

In [ ]:
raw_data = load_breast_cancer()

In [ ]:
data = raw_data['data']
target = raw_data['target']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data,
                                                    target,
                                                    random_state=40,
                                                    test_size=0.25)

print(f'X_train shape {X_train.shape}')
print(f'y_train shape {y_train.shape}')
print(f'X_test shape {X_test.shape}')
print(f'y_test shape {y_test.shape}')

X_train shape (426, 30)
y_train shape (426,)
X_test shape (143, 30)
y_test shape (143,)


### **Exercise 32**

Find the distribution of target, y_train and y_test arrays (in percent).

In [ ]:
for name, array in zip(['target', 'y_train', 'y_test'], [target, y_train, y_test]):
    print(f'{name.ljust(7)}:{np.unique(array, return_counts=True)[1] / len(array)}')

target :[0.37258348 0.62741652]
y_train:[0.39201878 0.60798122]
y_test :[0.31468531 0.68531469]


### **Exercise 33**

Keep the same distribution of values in the y_train and y_test arrays as in target array.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data,
                                                    target,
                                                    random_state=40,
                                                    test_size=0.25,
                                                    stratify=target)

In [ ]:
for name, array in zip(['target', 'y_train', 'y_test'], [target, y_train, y_test]):
    print(f'{name.ljust(7)}:{np.unique(array, return_counts=True)[1] / len(array)}')

target :[0.37258348 0.62741652]
y_train:[0.37323944 0.62676056]
y_test :[0.37062937 0.62937063]


### **Exercise 34**

The *df DataFrame** is given below

<pre>
   years   salary  

0    1     4000    <br>
1    2     4250    <br>
2    3     4500    <br>
3    4     4750    <br>
4    5     5000    <br>
5    6     5250    <br>
</pre>

The first column describes the years of experience (feature variable), the second column describes the salary (target variable).

Using the normal equation and the numpy package, find the linear regression equation.





In [ ]:
df = pd.DataFrame({'years': [1, 2, 3, 4, 5, 6],
                   'salary': [4000, 4250, 4500, 4750, 5000, 5250]})
df

years  salary
0      1    4000
1      2    4250
2      3    4500
3      4    4750
4      5    5000
5      6    5250

In [ ]:
m = len(df)
m

6

In [ ]:
X1 = df['years'].values
Y = df['salary'].values
print(X1)
print(y)

[1 2 3 4 5 6]
[4000 4250 4500 4750 5000 5250]


In [ ]:
X1 = X1.reshape(m, 1)
bias = np.ones((m, 1))
X = np.append(bias, X1, axis=1)
print(X1)
print(bias)
print(X)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]


In [ ]:
coefs = np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, Y))
print(f'Linear regression: {coefs[0]:.2f} + {coefs[1]:.2f}x')

Linear regression: 3750.00 + 250.00x


### **Exercise 35**

Now use the scikit-learn package and the LinearRegression class to find the linear regression equation for this problem.



In [ ]:
df

years  salary
0      1    4000
1      2    4250
2      3    4500
3      4    4750
4      5    5000
5      6    5250

In [ ]:
model = LinearRegression()
model.fit(df[['years']], df[['salary']])

print(f'Linear regression: {model.intercept_[0]:.2f} '
      f'+ {model.coef_[0][0]:.2f}x')

Linear regression: 3750.00 + 250.00x


### **Exercise 36**


In [ ]:
df = pd.read_csv('36.csv')
df.head()

variable     target
0 -1.136602 -13.152922
1 -1.418556 -36.316645
2  1.744814   1.744814
3 -0.232182 -15.822773
4 -0.489337 -24.081511

In [ ]:
data = df[['variable']]
data.head()

variable
0 -1.136602
1 -1.418556
2  1.744814
3 -0.232182
4 -0.489337

In [ ]:
target = df[['target']]
target.head()

target
0 -13.152922
1 -36.316645
2   1.744814
3 -15.822773
4 -24.081511

In [ ]:
model = LinearRegression()
model.fit(data, target)
print(f'{model.score(data, target):.4f}')

0.5224


### **Exercise 37**

Load the data.csv file into the DataFrame.

Then extract the polynomial features from the var1 column with degree = 2.

In [2]:
df = pd.read_csv('37.csv')
df.head()

var1
0 -0.542034
1  0.528620
2  0.625143
3  0.193978
4 -0.800259

In [5]:
poly = PolynomialFeatures(degree=2)

In [6]:
df_poly = poly.fit_transform(df)
df_poly

array([[ 1.        , -0.54203446,  0.29380135],
       [ 1.        ,  0.52861971,  0.2794388 ],
       [ 1.        ,  0.62514332,  0.39080417],
       [ 1.        ,  0.19397775,  0.03762737],
       [ 1.        , -0.80025878,  0.64041412],
       [ 1.        , -0.30353167,  0.09213148],
       [ 1.        ,  1.08617991,  1.17978679],
       [ 1.        , -1.1601817 ,  1.34602158],
       [ 1.        ,  1.03831416,  1.07809629],
       [ 1.        , -0.81530272,  0.66471852],
       [ 1.        ,  0.41601746,  0.17307052],
       [ 1.        ,  1.29711284,  1.68250171],
       [ 1.        , -0.43286591,  0.1873729 ],
       [ 1.        ,  1.05874434,  1.12093957],
       [ 1.        ,  1.13877614,  1.2968111 ],
       [ 1.        ,  0.99991287,  0.99982575],
       [ 1.        ,  0.108967  ,  0.01187381],
       [ 1.        , -0.39014048,  0.15220959],
       [ 1.        , -0.70064547,  0.49090407],
       [ 1.        ,  0.69831212,  0.48763982],
       [ 1.        ,  0.75157138,  0.564

### **Exercise 38**

Load the data.csv file into the DataFrame.

Then extract polynomial features from var1 and var2 columns with degree = 3.



In [3]:
df = pd.read_csv('38.csv')
df.head()

var1      var2
0 -0.016394  0.588725
1  0.754263  0.076439
2 -1.156829 -1.464842
3  0.177427 -0.174888
4 -2.501646  1.536316

In [4]:
poly = PolynomialFeatures(degree=3)

In [5]:
df_poly = poly.fit_transform(df)
df_poly

array([[ 1.00000000e+00, -1.63937800e-02,  5.88724753e-01,
         2.68756023e-04, -9.65142408e-03,  3.46596835e-01,
        -4.40592711e-06,  1.58223323e-04, -5.68203226e-03,
         2.04050136e-01],
       [ 1.00000000e+00,  7.54263324e-01,  7.64394064e-02,
         5.68913162e-01,  5.76554408e-02,  5.84298285e-03,
         4.29110333e-01,  4.34873844e-02,  4.40714767e-03,
         4.46634141e-04],
       [ 1.00000000e+00, -1.15682855e+00, -1.46484155e+00,
         1.33825228e+00,  1.69457052e+00,  2.14576077e+00,
        -1.54812844e+00, -1.96032755e+00, -2.48227731e+00,
        -3.14319954e+00],
       [ 1.00000000e+00,  1.77426725e-01, -1.74888405e-01,
         3.14802429e-02, -3.10298770e-02,  3.05859542e-02,
         5.58543641e-03, -5.50552947e-03,  5.42676569e-03,
        -5.34912874e-03],
       [ 1.00000000e+00, -2.50164566e+00,  1.53631585e+00,
         6.25823103e+00, -3.84331789e+00,  2.36026640e+00,
        -1.56558765e+01,  9.61461953e+00, -5.90455020e+00,
         3.

### **Exercise 39**

The 39.csv file contains predictions for a certain regression model:

* y_true describes the actual, observed values

* y_pred describes the values predicted by model

Load this file into a DataFrame. Then implement a function called mean_absolute_error() that computes the mean absolute error.

In [3]:
pred = pd.read_csv('39.csv')
pred.head()

y_true      y_pred
0  109.934283  113.175123
1   97.234714   93.383891
2  112.953771  106.184551
3  130.460597  136.577360
4   95.316933  105.626928

In [4]:
def mean_absolute_error(y_true, y_pred):
    return abs(y_true - y_pred).sum() / len(y_true)
 
mae = mean_absolute_error(pred['y_true'], pred['y_pred'])
print(f'MAE = {mae:.4f}')

MAE = 6.7918


### **Exercise 40**

Implement a function called mean_squared_error() that computes the mean squared error

In [5]:
def mean_squared_error(y_true, y_pred):
    return abs((y_true - y_pred)**2).sum() / len(y_true)
 
mse = mean_squared_error(pred['y_true'], pred['y_pred'])
print(f'MSE = {mse:.4f}')

MSE = 74.9471
